spring:
  datasource:
    url: jdbc:mysql://localhost:3306/metacode # ?????? URL
    username: root # ?????? ??? ??
    password: 5986 # ?????? ????
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL ????
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create