spring:
  application:
    name: blog
  profiles:
    include: db
  datasource:
    url: jdbc:mysql://localhost:3306/metacode # 데이터베이스 URL
    username: root # 데이터베이스 사용자 이름
    password: 5986 # 데이터베이스 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 드라이버
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE